### ISSUE TITLE
Global Icons

### ISSUE THREAD

**Issue by khornberg** [btecu/ember-cli-bootstrap-datetimepicker#13]
I like the idea of global icons. 
I am not able to change `date` and `time` icons with the global setting. I can set them with `iconClasses` and `iconText`.  Perhaps `date` and `time` are not the icons I think they are.

As a note, the global icons do not allow for the the typical material icon since there is no way to set the inner html, only the class name. However with the `after` pseudo selector, one can set the text.

I've been able to get material icons work with this by setting the config to
```
{
  next: 'material-icons chevron_right,
}
```

and then in a stylesheet
```
.material-icons.chevron_right::after { content: 'chevron_right' }
```

**Comment by mastastealth** [comment]
Was just about to report this and I see I was beat. :) Yea, I can't seem to get the global icons working either...
![icons](https://cloud.githubusercontent.com/assets/1221228/16491862/8d8a4808-3ead-11e6-848a-248c228bacf7.png)

**Comment by btecu** [comment]
@khornberg yes, those two are somewhat special. That's because they are wrapped in the component template. Any ideas?

@mastastealth do you have the latest version? I can't seem to be able to reproduce the issue. In your case the icon classes are not being replaced, but they are replaced for @khornberg (except the special two).

**Comment by mastastealth** [comment]
@btecu Yea, just installed yesterday, `"ember-cli-bootstrap-datetimepicker": "0.1.6",` is in my package.json. That's latest right?

**Comment by btecu** [comment]
@mastastealth it's working fine for me (although I don't have the fonts).
Try stopping the ember server, removing the addon from `node_modules`, clearing npm cache and installing it again just with `npm i`.

![image](https://cloud.githubusercontent.com/assets/7517745/16493612/1f6dbef2-3eb4-11e6-8166-3f585dd6f267.png)

**Comment by mastastealth** [comment]
Still won't work. I'll have to try a fresh project and see if I can repro then, perhaps it's just something on our side. xP

**Comment by btecu** [comment]
No, the options are supposed to be in `config/environment.js`.

**Comment by khornberg** [comment]
@btecu I think we could use the config setting in the component. Instead of `{{iconClasses}}` that could be a computed property that gets the config for date or time.

I like simplicity so, if we went the config route, `iconClasses` and `iconText` could be removed.
We could either add another config key to replace the `iconText` for material icons or just make a note that containing applications need to defined a style that sets `::after` to the icon text.

Since `date` is passed along to `bootstrap-datetimepicker` what does it actually do there?

**Comment by btecu** [comment]
@khornberg you're correct. Dropping `iconClasses` and `iconText` in favor of global configuration and `::after` (when needed) is much cleaner. I don't see any problems with it.

`::after` is acceptable. After all, if you were to use `bootstrap-datetimepicker` by itself, you would have to do the same anyway since it only supports classes.

Assuming you're referring to `icons.date`, currently it doesn't do anything because of the wrapping template. Perhaps the component could work without having a template.

**Comment by khornberg** [comment]
Cool. Yep I was referring to `icons.date`. With the global config, users
would not notice if the component worked without a template.

Kyle
