### ISSUE TITLE
It should always return moment dates

### ISSUE THREAD

**Issue by vasilakisfil** [btecu/ember-cli-bootstrap-datetimepicker#5]
If you don't inject a moment date, then the addon returns a regular js Date object. Instead, it should always returns a moment date no matter what, unless it should be null.

I think the issue is here: https://github.com/btecu/ember-cli-bootstrap-datetimepicker/blob/master/addon/components/bs-datetimepicker.js#L25

**Comment by vasilakisfil** [comment]
I can also work on that during the weekend.

**Comment by btecu** [comment]
I did that on purpose because I noticed in most of the cases it's more useful to have the date as a `Date` instead of `moment`, think Ember Data...

**Comment by vasilakisfil** [comment]
I use ember transforms so I have no issues with that :) Anyway you can close it I have solve it partially but it would be nice to be more consistent.

**Comment by btecu** [comment]
Although `bootstrap-datetimepicker`uses `moment` internally (I think), we shouldn't leak that detail.

I totally agree with consistency, but unless you're transforming the date, you'll have a `Date` which is standard on the client. Otherwise, you have to intercept and convert `moment` to `Date` before saving.

If further manipulation on the date is required, it's just `moment(date)`. Your transform probably already takes care of both `moment` and `Date`.
